# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/voyage/code/yasuo/huffman_con

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/voyage/code/yasuo/huffman_con

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/voyage/code/yasuo/huffman_con/CMakeFiles /home/voyage/code/yasuo/huffman_con/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/voyage/code/yasuo/huffman_con/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named yasuo

# Build rule for target.
yasuo: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 yasuo
.PHONY : yasuo

# fast build rule for target.
yasuo/fast:
	$(MAKE) -f CMakeFiles/yasuo.dir/build.make CMakeFiles/yasuo.dir/build
.PHONY : yasuo/fast

# target to build an object file
big.o:
	$(MAKE) -f CMakeFiles/yasuo.dir/build.make CMakeFiles/yasuo.dir/big.o
.PHONY : big.o

# target to preprocess a source file
big.i:
	$(MAKE) -f CMakeFiles/yasuo.dir/build.make CMakeFiles/yasuo.dir/big.i
.PHONY : big.i

# target to generate assembly for a file
big.s:
	$(MAKE) -f CMakeFiles/yasuo.dir/build.make CMakeFiles/yasuo.dir/big.s
.PHONY : big.s

# target to build an object file
huffman.o:
	$(MAKE) -f CMakeFiles/yasuo.dir/build.make CMakeFiles/yasuo.dir/huffman.o
.PHONY : huffman.o

# target to preprocess a source file
huffman.i:
	$(MAKE) -f CMakeFiles/yasuo.dir/build.make CMakeFiles/yasuo.dir/huffman.i
.PHONY : huffman.i

# target to generate assembly for a file
huffman.s:
	$(MAKE) -f CMakeFiles/yasuo.dir/build.make CMakeFiles/yasuo.dir/huffman.s
.PHONY : huffman.s

# target to build an object file
main.o:
	$(MAKE) -f CMakeFiles/yasuo.dir/build.make CMakeFiles/yasuo.dir/main.o
.PHONY : main.o

# target to preprocess a source file
main.i:
	$(MAKE) -f CMakeFiles/yasuo.dir/build.make CMakeFiles/yasuo.dir/main.i
.PHONY : main.i

# target to generate assembly for a file
main.s:
	$(MAKE) -f CMakeFiles/yasuo.dir/build.make CMakeFiles/yasuo.dir/main.s
.PHONY : main.s

# target to build an object file
small.o:
	$(MAKE) -f CMakeFiles/yasuo.dir/build.make CMakeFiles/yasuo.dir/small.o
.PHONY : small.o

# target to preprocess a source file
small.i:
	$(MAKE) -f CMakeFiles/yasuo.dir/build.make CMakeFiles/yasuo.dir/small.i
.PHONY : small.i

# target to generate assembly for a file
small.s:
	$(MAKE) -f CMakeFiles/yasuo.dir/build.make CMakeFiles/yasuo.dir/small.s
.PHONY : small.s

# target to build an object file
tempwindow.o:
	$(MAKE) -f CMakeFiles/yasuo.dir/build.make CMakeFiles/yasuo.dir/tempwindow.o
.PHONY : tempwindow.o

# target to preprocess a source file
tempwindow.i:
	$(MAKE) -f CMakeFiles/yasuo.dir/build.make CMakeFiles/yasuo.dir/tempwindow.i
.PHONY : tempwindow.i

# target to generate assembly for a file
tempwindow.s:
	$(MAKE) -f CMakeFiles/yasuo.dir/build.make CMakeFiles/yasuo.dir/tempwindow.s
.PHONY : tempwindow.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... yasuo"
	@echo "... big.o"
	@echo "... big.i"
	@echo "... big.s"
	@echo "... huffman.o"
	@echo "... huffman.i"
	@echo "... huffman.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... small.o"
	@echo "... small.i"
	@echo "... small.s"
	@echo "... tempwindow.o"
	@echo "... tempwindow.i"
	@echo "... tempwindow.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

